%macro transformData;

/*
 *
 * Task code generated by SAS Studio 3.8 
 *
 * Generated on '9/29/20, 5:40 PM' 
 * Generated by 'mafiga' 
 * Generated on server 'L10B236.NA.SAS.COM' 
 * Generated on SAS platform 'X64_10PRO WIN' 
 * Generated on SAS version '9.04.01M6P11072018' 
 * Generated on browser 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/85.0.4183.121 Safari/537.36' 
 * Generated on web client 'http://localhost:52089/main?locale=en_US&zone=GMT-04%253A00&sutoken=%257B477C1EAA-6E31-42EC-BB6E-8A03E9E91A7C%257D' 
 *
 */

proc sort data=WORK.MYGOOGLEDATA out=WORK.SORTTempTableSorted;
	by YEAR_NUM LOCALE_VA;
run;

proc transpose data=WORK.SORTTempTableSorted out=work.MYGOOGLEDATA_Wide;
	var VALUE;
	id INDICATOR;
	by YEAR_NUM LOCALE_VA;
run;

proc print data=work.MYGOOGLEDATA_Wide(obs=10);
	title "Subset of work.MYGOOGLEDATA_Wide";
run;

title;

proc delete data=WORK.SORTTempTableSorted;
run;

data work.MYGOOGLEDATA_WIDE1 (drop=_NAME_);
	set work.MYGOOGLEDATA_WIDE;
	
	IF YEAR_NUM > 2016 THEN DELETE;
	
	YEAR_DT=mdy(1,1,year_num);
	format YEAR_DT mmddyy8.;
run;

%mend transformData;

%transformData
